services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-dumps:/docker-entrypoint-initdb.d/

  adminer:
    image: "adminer:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
